// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0gRzyguBEWzV0J_N79taTaELGDsTfYO4',
    appId: '1:544436452328:android:ed102b99e5b1f8d842425d',
    messagingSenderId: '544436452328',
    projectId: 'live-stream-74918',
    storageBucket: 'live-stream-74918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqR1MEYim9w94yqRJT5ImraiYC3xu66E',
    appId: '1:544436452328:ios:be8844eb9e1c2b5a42425d',
    messagingSenderId: '544436452328',
    projectId: 'live-stream-74918',
    storageBucket: 'live-stream-74918.firebasestorage.app',
    androidClientId: '544436452328-pfj6enpaus1tbtbhs1b1am7cf7legvm2.apps.googleusercontent.com',
    iosClientId: '544436452328-veq0skptfvegjqer4c8i9u2hf2ot3pql.apps.googleusercontent.com',
    iosBundleId: 'com.example.liveStream',
  );

}